### ISSUE TITLE
合成速度有办法加速吗？

### ISSUE THREAD

**Issue by jintian93** [atomicoo/ParallelTTS#3]
比如tflite，比如换一个backbone是否有方法可以加速一下

**Comment by atomicoo** [comment]
可以看一下 [速度指标](https://github.com/atomicoo/ParallelTTS#%E9%80%9F%E5%BA%A6%E6%8C%87%E6%A0%87)，目前合成阶段的主要耗时主要在声码器的部分，所以可以通过换更快的声码器来解决合成速度的问题，至于声谱图合成模型的速度应该已经是很快了
