### ISSUE TITLE
  MelGan 模型

### ISSUE THREAD

**Issue by neverloses87** [atomicoo/ParallelTTS#7]
请问有普通话的bbspeech-melgan-epoch*.pth 预训练模型吗 或者是要跑哪个脚本自己训练

**Comment by atomicoo** [comment]
声码器部分见 [seungwonpark/melgan](https://github.com/seungwonpark/melgan) 和 [kan-bayashi/ParallelWaveGAN](https://github.com/kan-bayashi/ParallelWaveGAN)。
